# Generated by Django 4.1.4 on 2023-01-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_alter_friendchat_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendchat',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
